on:
  push:
    branches:
      - master

env:
  IMAGE: kuviman/dock.rs

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Push
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.IMAGE }}
          tags: base, linux, latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  other:
    strategy:
      matrix:
        type: [web, windows, macos]
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Push
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.IMAGE }}
          tags: ${{ matrix.type }}
          path: ${{ matrix.type }}
          build_args: BASE_IMAGE=${{ env.IMAGE }}:base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
